# Copyright Aliaksei Levin (levlam@telegram.org), Arseny Smirnov (arseny30@gmail.com) 2014-2026
# Adapted from TDLib at bc9c263e2bfee06aaab41e82db51a103376030bc.
# Scope: filename sanitation, Unicode filename predicates and extension-to-MIME metadata.
# Complete BSL-1.0 license retained for standalone staged copies:
# Boost Software License - Version 1.0 - August 17th, 2003
#
# Permission is hereby granted, free of charge, to any person or organization
# obtaining a copy of the software and accompanying documentation covered by
# this license (the "Software") to use, reproduce, display, distribute,
# execute, and transmit the Software, and to prepare derivative works of the
# Software, and to permit third-parties to whom the Software is furnished to
# do so, all subject to the following:
#
# The copyright notices in the Software and this entire statement, including
# the above license grant, this restriction and the following disclaimer,
# must be included in all copies of the Software, in whole or in part, and
# all derivative works of the Software, unless such copies or derivative
# works are solely in the form of machine-executable object code generated by
# a source language processor.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
# SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
# FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

"""Pinned TDLib document metadata; no byte sniffing or host Unicode/MIME database."""

import base64
import json
import zlib
from bisect import bisect_right

# Generated by tests/fixtures/document_metadata/regenerate.py from pinned C++ predicates/data.
# Encoded entries are (first code point << 2) | kind: 0=skip, 1=space, 2=preserve.
_PACKED = (
    "c-pOf>yqlclI6Rczo($_-JVzJn3yoO0q?@t+cuY~iFx-~Yb8*C1=QEw5mibnGj*3znJL-)=YK9fq7N@v"
    ";6M5BLjS{yf)6hSjI$3f2|v6PFbhBYAi#h6;fEgnWBg|yew2O$;0wSPq|rx^Ek435`G^)i{<Dub_3<Bl"
    "#2Fy)i5Gq(zK8!9|Jg?p`1l7N<tE54i9nB|k0e=qq_Kzp_#;F48Ou-o2mv_#6evGq9WpTcqGrfGSfE@4"
    "sK_G0Q-CakAi`7RGeFG|#0b#FAc~1gkSt31#QMkHf<eH5O+y`nI0zYlFGk@3>mRTI;UY>9AeS)q@D%%K"
    "d>o-a17v_8{Xk(Ef`m`0_Yp;l_#=vmOBUcuiA&Rv0dOgLDasZe1K={|l6gpx`NW}b;srV-ULe1Ckp&;I"
    "7XrtDLfOFiXcmGP0r`B4N*t0U!uZA!`Jxomh{F+ONRcs@3{R-f0s+Pt0S1T7LO=p~C|RVWlFy4cj2M@M"
    "<tDxloF8ylnat-v1~Hh~@`No<QVw#eC$u-oFo#la!2m;%a=N7+$J<Nzl=2Bfk#f$ZKBGR$O);zpm^KLc"
    "gx)}a3<A_I4bkl>`WOMHO@z|Y*yjX7g;GwjG|?003j$CRCQCA8fDAt}Ha}xKvJkmoZutxljZh@I9#o9k"
    "M;4>v8HYPVA0t41Sxf?_a+ZXMCK01(YL;Yt!o<wdg(h;q02ySM%INw9gMhOeROHHlRE!&f_`_RpE+h1O"
    "hG-ANlwl}LD5`O$qGqIeO66fLBlIoI7zU!IqM~~}WSKDZV}<1L17D%=p?D%a$HFUZu<#X<pVQo1geoyq"
    "iJ{Vls$m$CCyba6R*6EE6=JLrrs7wgVaj|W<r(?pj{@?r>k&qJj)jlKqn2{1GSsvBhYJv)a*M@-$;(ij"
    "NyO3<<&aRgVPf+cbCIFXnxqtli%dO}`D{g|R%B{LrdDKXMW&i#G!>#04j4n$+~Ybz$h2${L(CS0ESJS2"
    ")QEUo#t7L)Pofut<}no2XAgM3()zJ5si-OQ4_Hqx@b#>61NJ;5Im-<L=B%Fg)bpNt-s8eVm@#d%AWy`x"
    "L&&rglnlueMdFFYqdLdpk5z80{A2OQA@h$Tg{p0=ma69wGB+*|gsJe^LZPVYy_6&9rOGoEXUfs^QstJa"
    "&S|P=rA?JKRoaX*(92W`mls0yp2p70*sK16W9=_EyL_!3f5F=Ni&*$XJgJ_Ur|)qTd{6vZLB7X6_q948"
    "`N$Kn-yk?Vg`@`TF-Sw^7II7xk~3oK5bBw2L`eRKtwSh$DjxQaAFK3O{IN=;FylmEp0V;*Kl|!uOpS#?"
    ")>AXzPn3$ADMF4l#Hp{4{HZ65FO2d`RnJttkt)wj`De@_Q11l`u9QGCJXnOnv(*SwhMXY*cMF7>crsEw"
    "&Vj%azsC^?q*_3DcnZbCbrfjk2R?f>@WttK-C=?Y!}<gPXDKE-F@a%J!$7$O%1yHu8@)oMjo33mq*7we"
    "mVm+>A=i$!dW4*BK^$91e8Rp8G>5V4Gp%|uP)`Pu7zmk9$~l0LsU$rDN_e!HJmJEgV?8H&=1L49bP#&%"
    "+fcF^A$inSp(lQib0hS`?@`)^zWBLcArziFB}3vR0WkF}WZH-lCXB=xQSwV$LCA4ONFFL^9)vNeRK6I-"
    "3Yn+oL#P!OYQ=?_o+bC91xF2G%#dY83-)BB^#!3W4D*MWAx3SCq;?_<6bc^;&;E(jMl2fU?~6xkD$<BY"
    "p>huGnbIKAz5sFMD`Z(wDm*0yLgo{(&XLAF(yjr)##Av|9cg5-1et?cijbvbs&hs;5M?SQV=1x6QI5Sx"
    "&s_Df=3X4JZgI?>k7LeBXb8k4oF`bUdgdI9wFe;-CKHAwLT^?WC}iDYs)PvbS@}z*NpC~Qnj{ORN<6k5"
    ";?`G)wkJMIPt>1@`ZEbQPm+M+k|rDr=tv8Op`Ih*S#yN3!i=H#wPQk+OKBR2CnHa$IRNz)`D7l~LPiA-"
    "VXWswc=mASbL}9E7>eKb_00L4`Rw_ON}rcS!c%=k80wjI%d}HuT6dY&U8db3%Qy-d<rRcI4Hjuc5cV`$"
    "7Ss}b=^hACXW#4xp9+@`3FavTUNQ<H^9iWQB1C^ew9^I&SO*Gtg-R8pbnFTdd8lJz=k}Nuou!aDa6dw5"
    "&oo&=YIh82RB;3m#x$&a%r59&3mRGw1PV#zZqATAYEh^bL1RUpVI)p!O1@S%LK;gUXP_T)2Ko{02ZWeu"
    "encG{p~ui?%_Ev~2*u;Gy-}p+c)@4R6NcoW_KYwip8b!I{IU8l=GsTde#06;tzyb0Y+|fK94`2*w!|Ux"
    "i7A1xiFpbGVmJe_i9ze|6ZKM}UP>r85JIvs6oxq@oKXl_I_%0&A@Kogn{XHQlQ`rvm32RXnSe0!6-MOL"
    "oJqOIA;fyb_6V7eFeaY66?%m2O}WcstAtF(Rw<h_7Byx4G1SN{rQ}D*9>D5As!a9FxYHpQpZ2TIUdlqu"
    "WQ2j9S^tds7($LX=0EZALZ+@g`+8<uGD<CkvG9qWRSI{1PUKK_Fl<)nQ~|?K&zPS9m-+`bTht$6pl9?0"
    "Ld-yfw5G8%eTC$qHNh}Ym@=dxjF9}?sS(m0;B&noRQ}PzQy42GUY58|-JT)&ssA8M^qdhNtK3+1lg*8("
    "Ks?<C2!*G-LZ~`ZVk1<ZS-`S5rce`T`Ul)M83G?r`UR{gL$;a)Gi2!`Go*(g2-pMA5Ku~xFlX)f44IZ%"
    "Q=r`+q4G&pN~(Nl=OWCArxhP)?IWZEBFL0~Cf@|*IYX93dCp?>Opk;#2ZYQ&q#Y4Rb3mB#nLBA9%>f~M"
    "21_cUYXb8sNGKD6M0HLme?nPju+uR2AT=;jPy|qCgqSU1OdAs+{TeYPC&FZ*P|qo;zVNh45TY#z<^7;m"
    "7Rud#IhWBD5-A^*6?5lBn2}0nP#AMgA`D68N=KM_3YjYP0)<RPD*$1{n!sddsG4L8ro{%sP&Hw%QiTZ="
    ";yK~G4J8diNrN!sDn`gUWVD{bETGROW4|Gc^o-ey5aWnYsVITbDmr_Rv7T89OnjeVrf2ja=6Xce7cDr1"
    "iJpaLo(NHTv|y_diYE~dTS^rv`iNu?Mza2>7A+Vutw#+fqB5i~W|)$nD*_?pTZGM(Jd`;R7u!c7KLu(g"
    "9V6vZ^w^2iGSW<5zVxC)1X3TQvq6{Oh7DyR6fNW?3&7o%z+%!LFegKT*oy_EexM~ns)WR&3?Wbno-~5Q"
    "j7or5F)mz!&@>h*WK>*21E$QxM$5#Raj%EWr;1Eq+D&9YoW7hQ0MdedFEOCxK7C~bp2bvaNic#;dCD@z"
    "N>WpN=^TmA?HxcmKY%Ll%kBhFFUbK(AQo6jhNOa$n4JU=8A~LZ)g|za#n%7?L1;kL4dh8l0_(Ftb|OHk"
    "%n~&Wf=KFIYRJrD(iH)W#riCiftHxnk%V&aB-ngB0aX`L#6V=U)PU*&okZzERX3DJ0lTYe7ScZ^AQr1&"
    "m{@Y@wgjT3(nmun+5o-*H9C~VPhd#(l9?k|ITp*zGi@!37Bpl4R3$Sz0OB(sXCzNpVul8Q`qNAe0Im)I"
    "4R|CCG?5A<5DTd7ku=goE?ojk7pbo!n;{aS1X?SxOkx0aPrOiOv3zp?-0(5@+~onN_F>bF6q7oNO_tgN"
    "_gcoXKpK}CjU7{(0svJA%m`|<k<@>JNHNcpHtx~{p~W!Z1WL#CB#;RS-O;o>(fn963Uz_RbU#xBEuC-a"
    "IC}(Cy7V_}=2WM!o2&FJ5N8(a$RLZQW@f52HdrZw@?R2UR01V}s0R3=nfAD#>z;u6HG6d-^>Sfarj$od"
    "t&KgYS+U1`o<Pc^N52e#6jd6!1T-xGQj5{B1;{Ly%xDy31hLX(#wi6J8X0xd*tgQ<BO(YbmIVfwr>|Zj"
    "5G_b8mRig>1LF);PoIm6I*{t(tIuMyO8~?fXimhi_Q@H<s;8V30@AYSPZx-!ZJPp~D$g)g&tm~)0%<Cs"
    "hDE-rE9;vMCk;nr6^x{s0tAZ1mM+maa2gP#s%Mm{*6~7_VN@+98i!LrvmoYX17LF^He({TanRNdlVG7)"
    "ka%iCqT?q3^%5jmB%tz=STiI^WO^it`ZGy1eu=d`NzLR))n|#-Gf6F-<}M6zFEAilroK+3%*SRY0H}m?"
    "p*&NY$*HUm02)~^)oF#snax&A{X{?=nb{a+R+r5BEaS#UbBB2n!~(HmflQu7aE{580SF9;Ci{=TVzF$e"
    "=uAtMF3OZHwpeU2YFz}JJs3;n>CvG>AiIkGO_^P6dqO{+nPQ^R<wX75(uK;?qc#sf1%xJ=EHYmPq3y*!"
    "_hK1t0Vh%7%j6{p&6*QS7?^EGxdfmV(Vi7ZEdke2B9EznGK+nS1x8Z^{n*UK#FD302`ziuwE;X0K%gZ9"
    "pr!;oeiFz8G%5l0MgS_-0I?;f+mN1DjYFVWhn+cAy3{huR4g`Oa)z=q6Ep6yMJkt2bDnz@(?!-xQ7B6|"
    "GR`Pgl_Dy61d+v3CD7DQB28$3M48DnO)&b(%qkIU>q%m{B>-eQClbE|7So_65~=`7m&jL;*fx<Qp~jCJ"
    "E`ioxl4zDg$4!+Bk5vfNXGx|`PU(v$&;(0;b!2K&Dh*XntcpMeyDWJu4k6`f;d!EHTE0n|shMVP6BtsJ"
    "kaLPalOdDrfij|*m1%PWNDZl;fb0(qSWLbHm<WM@1~m)SOPNjfjG6#}YL-Rn)-2If%;XZH2oYy$d8X!l"
    "NY$_`4GgF!q_fi-;rRv<0VW`jk75xU3zs(fQSOLEU@Sb2Ac!o+@guNUDiB&OnoFt9><A*oB(qYJ8qn23"
    "amGed&!>xYp%PMGNR2IlvQ`^XPhO_f^Hh24%)WuhTq{NkEfy)}%lU#WJQRrJev!(-qhi*@i!3v3J*m#4"
    "<e^dW*l4j86kBp0lL#nlx#^&D#VS_A0U(c!M^jlqoT*hJRZn=<FfR?yK)Iw=I?wM3GI3^Bm&|-enbjq;"
    "MrW2TvzkfE1CUS2*Zd?%1vDIVQVOW@CO83<96&U!Q~))_*GeT2Ezl6dXb%m<0>)yK!Ss;S#BXYP2!Uu4"
    "zXTRjm(we0z>u06&=?m66qAPvv)am|RVvR}Bw*>JMDa*}VIUUJ_yuz7q2GN0$yNf<Lf;&4$}G@s51{c2"
    "J&m-i7Xl5AtQP<|*;4b60x0V+QYVMzyu%J6kZHh8{1RjWx_%PLp`1pNgHRl_xFV}yWStd-x}KuT9sm-D"
    "sSY6MFr*}cs9GqNYH3GOcmT9kuwNzuT53_IT;weQNHr?4Y=ktC2!dSKh$V@NO_Ic7sl`-mlBn{D-JUTi"
    "OrTusHVp-ufaX#nuPcCMmZeG{F`A|}VyTT-YO^)9flKAPhDcWXQWG<&4O}V}m2z6iV@;GaHiu~(o`E6N"
    "_B4(RsVb$mQd3&H0Jb*MOtEaSID=3?Bb_ZGL#neflSBYQ+60s9hd{lQNwrNgDIfrv6DGEi3Hv%*sIRky"
    "T+;v+qw|I!vKVJ%=BX|Kfn2_HQxGJEG(WH^k(rPKFq+n1=7kF-kXIidllwRd71M~(jchSXM}MP$oXgtd"
    "0N8bzPPGLR0S-W>Lv8|P?MpOgI_DM;P0I=LYoT0x-~869gfD{%z)Fw`j=j_}(?ZBhY5;K75u^h0c<WG{"
    "Kz?yEa57VrFdC|SVEqZPlnP`5lC1<{(L%`NHHBD_-I(d@lpwH}SVE~40P>lK*5x_{6%dQeD-OGy@$@S~"
    "MoFE_bfU#OW=faIe+{FRZeVXgZ$-e18i@e??mTJ?2{@Ap=y*m=#DX0wl{4D>(-t!yE=*Fo%wrxj5>Sr>"
    "NLWyu+SN1NN+F;NnU+u{z;uZx-+ZE(1;FYGSd89mDCDesqWc;GqQ#broa@l;76t+(=cx!mD#x-s(e$ka"
    "22$OITZpFf0aNQ~f+{oLmlHaq;RoQU5*iKyI<)DxVU?mloKY%TtPTP2LxI4M0XgG94U2<RNUmFeP?_nN"
    "l|VfaCn^^5b73G7hz&_MJD$-ZRFAs_fO*JcnpZrj*B!r@CKSXv4R->}RsoBlE&{2*nUj9=FrX4eK>ssA"
    "LcmTY@FRi1Vu8_&lL`m{`Xz)uM$Sm{GsJ#E*L9>bbOO4hBb}B5@Hmx#c>>6_A5o_z$SjsA9j_<C&Y<8V"
    "p!=Lw2xFlf<@5-K0*b}F{X@Xg0hmi-uKa{XIstD*0?>&^z?xxK!UQ8=f11i4Lf2=%B&kjm5^8M(>Lu9U"
    "tY@Ng;E?BXfdS@{rQ*zJuMikbrvU_!fO6rA72s$lx@$)eSd1gh-OM*&G+tXZHJgB^6VL{EBtZ}p(0xPT"
    "iIe)ZfYDf&R0cQz#Wn%!lIlVmfoHKGFd)vza-r{#z{-nMp2y<=0?~ZB^aPmB*SM#W&~%=%4XGU0AvL*7"
    "K&AVUTBI|#FqJ_ZntleL<CoM=tc27`NUelSb)g6Z2sG;eR6^h>mw<~hq?*QDBC3-Bn&rHL$?_r{<N$=B"
    "0dZ2k2w04BiGnr};Asp1O9vm%r7~UXBVb<x=y-;gLj*#LMLdb|jML+dDFPkXcsv~y5GUrTfDUaW@&Ks!"
    "gti+BFr6Q%JRLR?1Qv@8D7h|E5rj&vuH&(iXJ<y_gxV7tVCizO1Mrd^0ecWYG`VsCqS%1WpJLrBhM|zy"
    "36v_B#0vvDw8}JJczHB1kO~AA3oK@wu}aA3s3YLX5l?(P0iGQJgoea~21o)OYEjE0ILAUyAhMV)dxyS`"
    "vqHQ29op@0G&3-e3IvL!%7w>c0=_T6d(aDc3kg(u#G}-R*E}Nu9)J-rUA#~UF}<$@YD#Q*#+IjUN(;mS"
    "sm0QBEEC8qo#p9SI%*IEp~XUr@m4oMU?3H+5<Dxx&ii6syAe<co|WKP3A~0QAewKr_N~^wmF`>Vey}hQ"
    "7*Kh>dY+D90jrB|b@8n(eq!lT%SC+_2UbF0B?N)RtbIXbvDjj<(gl`FX!Q)Oo}u-ijcsgW8{62%k>wd#"
    "p0U#D3IqYuL5pMzfTxpC2T?OvGP=2*>0l-CWHTprZ8Pz7%0|Ge<$-R>1Bixwh_4RBGMc!B^MX3;8(uw!"
    "+(qfwNa)u{Z5&c|GOv;QI$MwFR9&25B*;?{!bsQs6KU)L^@fG_zd!!(zo6dz>wo<#@49VW<YV3L{^PJK"
    "=i7GN4>ND(&w_t_{3|G%EttmYG>Tg9f^se-X#+@gldr4)IL#OXZtVkisLQJTk6_((zHr?g4yfe&q2$vn"
    "`JNSR)AiLbR3%vQd^zFC_v5DRk9l9smi10d1)26`-I9zLam}lQP2P!Vc*QhSYceg5Q>JBoY<pF(cp!G4"
    "HR$8m&x)!a#ZfpqIB%*R@m=|~%bU6w=42ytH7%^D9y+DiyK*e{MZ0Xb#xNGoSbDX*?5<sg=b|C5>Rf5a"
    "v+nb5LzdOFS6A(BoQ+>y<%z+SN4;$3O<NY$>6<DqT?G+8A3Amcxa!A#ZHI9v`npq})~nkQuU9KW7EY{_"
    "w|7;cY?sv>wAl@1R_}%}-)^gZhPr)Xp8xy1RzvF1kw<x0&Pf5ishtB~uXBdv=ssN>yRvWVa(*stmiNV`"
    "KB!Z=uE>i`by<swU@q_KRW*#paLH;iPR(%JDlzv@S3a<Pi`>c97t=BCtBQC~hsgq1ce9~h@A7fqtJ1^j"
    "y6~+QgGOLzF3rHG44QyL>zuR&dSX7*O}G7;lZTuqXP)n7{n$RvU!wkfk|g6Junq=1-tY{E!odUVmFMIf"
    ")v-R!*I4&j%<Zn)X~g!|$+^sjT3vdm?;58k!>_KQRuSMHWs{yy6knu%uUs{$draW@s@_&ZRbY_j<Rka+"
    "OYTA3N9XL$zuVosTDI*cn3j|7WP{4~xZAclMcK0G>UP3nSWwHATilR9a^tAN@U<(N?YwOMeO%grEGw71"
    ">8pHu*cJ1oWa@I`J9t+6KlM25=WRZG4PDQ6bIZABY>TlPXTyjLIg6Lu>6W$Jw*68x!lzWHz*tIDESv5+"
    "_Iw70UF@iGk15vVpH(j&*Hpw#a;U2#nlx6;FeejPr@QeIBhS5iIgwM3Z60r?Ci-bE1n}-WMe&~&SNsSD"
    "u7|?&^2W8Wi|xJ|`~5J^i@e7YY?qj%SY5kSy}qRT{)g#i-KWxqr88l>`<xfyx^MTLxK_X7TK|fx`xV#z"
    "H(V2~iChqqAl$1GMSi<EGDe)MCS%c+`=*<Bwu__ZTou{(TXw1#Mt2>cAk863NC($4nM{LXsr1YIDW!i("
    "8J|+VpHUuXTQSX}toy1MTVp>-7rtc>?kxO^a#=KkbHE|E@&a>?WHL@=+pZc5Nw%W=tiD{`SCw@RZG?!q"
    "F_F2cANz_p3}**Lbz6@YuENR1deuA03nEGvQ`t7TbZy337e~ANgFZTQ{B?2s-B<fc3=~SxTu`BW%Wf}E"
    "hMx4S`VEX_pC7Ls?CO}J-j!8fZMQjDs@|oPpY`!#HC6h7dsr9i<|@zl49v!{mkCK)<DToAvDt2_trpCt"
    "cP)s|vYLM)8>^b6=xxtPiWap~k=zYXNsrZ14XanARkL~+_6T?NSYPzKqTae|heFr+w%6>~=1#eie>JUC"
    "2|Nyu{q`q6<g<f1XZz{ei=eI-kW0W}JDOv*F56sI6ZpHg{9V4S#?cD@9N)5IFYC7Xh5z`Lp9b7A-+dbY"
    "=^ek=I)^p`y2jVNMYTiI7P211Q$7xGW9wZr{|>LY-ne?{3)8$k_Am)xV`3L;n^{xs_ToR?*y4-<*E*G-"
    "x|x$gdh=RE<Gy$ik?3HP0xqrXth5zf_aITb$H8mzLdy-}5M~Bh`qI_2m@L#g#jtfQ>0aH`PgmwCT4WG_"
    "*G1odbz{40$I96m>-h}>xQETOb;CxK$w&=0RD*Luw@uUTE;enU6=as%FbMH_uNe+M{0AZ)H~(Tk8>*^N"
    "=KKE6N255<$H$dG^^921POpnUo$d#+%-MS|<g4wub&$7ZeiqDS?ox)RT<wQ>Db1qHoieaA=~w13v#Y^n"
    "gsjS82c<!xxy%nuyWc%#bU|NgvwRdtWm`~XzR-*QRohEfch1Xmr<SG5SilxJ2jx;gSw1l+PF3HY=A?tG"
    "nwkT^)%ot?Y!K6A0hU#_ZNFYC<z>~sTNdRicS)_1Ie>(|;O0=Sryc;{?sv?xeo&;!`gIT2!;9%s55_XS"
    "X(Bkj-?02STxFu#_UEuS^xlczZeNSTvRO|(bcj`G-0-RV#Ptgux@?9wb>F#mWnw{V9|xrw&OS+yp6DZF"
    "n1j5>hB3||hWobK<;!hV&OP5!x;DbLt9F>xtF~|QahSC$C>zx^8)gbIUSKBFyERSkGesGW&uclps^w)n"
    "ch++JAE@PxzEHXbs~y($ywo^#E`1)@vsV<_>D7p`<)Z-_t_y-9cMBDJn2-5dq>0yzsDGEz63Wpb6UJNF"
    "HBNTRW;-L6wBf!k<6ziL`G}uylwd!Zs*khqu)O-CE*{SFwp<?SX;lyOSCq%q-Cn^svFrOqcT{(rR`=MG"
    "cu%fT8M<~{L5j>tCeuqHQx#CYdFp-F_T9ef^Z5_$%$J18Q$Eqod|CWFKhePF^i1vALtfVFW==AhPOq7$"
    "zE!K*wXJq_F;tujRUNy?YfRsK*m5MQZSi`1t7hd8c}+Fu=TWYt^E6mF9HD+yq`oh7^C+H(I#1H7`F@jY"
    "yS<;0^}2=vFgwDO8$^HNK%fWkYHe2C@amwT>h_O|iKw#&zj{nt6;1w=c5t1HRl|3^-nGG{nM3|eb`1Na"
    "x!A<!8bwr|&QkfVtMNCbjW;UUQ1OA-!_-wm94TK@%I?r|SFcXh>z%GTJuYryh#z0hTdULK=<`&gI`S~3"
    "GP+BJs=hm(o^6+Vb=r6El;=k~TK)70ME}_5)Q?u-;l_u~7;s7AWX%>%^m6K;#D>DB8&SMk4tJt!l@H^x"
    "E{9E}R<4S2e0t8rjcO>cH}&~;E>0$JX+`yr7ju%pP_CT%F{jX~`aj!zzbiJb-KxR>walb~QQz*z88#%^"
    "zN>Zg&hfqO#8<wOw5!dH<;mlr4F+8J@EIX`Mo69!iYJ76s*;_|2fW(eoDC~N-0k_wN<wnAbsasy#_M_Z"
    "xjN0sK(@PSwbiuR9-sMj>O*a*PPeASs;QA(bsEk+xBa@KZn-#D%{$lrYF9W}+I7Ag=A?qB?VVG*JKay("
    "jysKVe_QI{EOjX6$7*?=eB>JM3((=@%6U4s+U`$d-Bk0lA7wSZc6P1y*dAtV$*=<I&eOFzjCYy}<G?x<"
    "iSrti7J+d4j>UO6w%UJxe_a;)+ILNab=5-6WbM|$wNuu?DnAMJB+12Puy)#K>%MId)hsUx8Ny_nI&sEa"
    "+vs}YE$_R}dbZwRn_TX(J?T_yT}-!-HSNS(6K`E^?{qrGfvsFihxZ!RI<{O_CwCj63-n*J3Vq-9nq2Gk"
    "(#^T9mQb+Hdc%4>yyAk=Q&wuydVIw<wz?{@-mIQ?@Y!{{zB$}l%Okt4o9C%e{%)+tui05+BLBp*y}q6p"
    "tQ%+l$a%Nk?R8INIyM&qc)E>qS=prx-9%V-k3|4;DgLj!1M*e%SLER(xu49up<fSYN;mbi8+vvwyRUvb"
    "HTuJg4&VK`Y(wjQdWgUZT^c()IZ)PexN3guF`t?hLX!4k=sBrwhkZQWFPM>TxAoyx-fNT&^*0Hp$J(uB"
    "39V00X7bK-t<AmTW#h-*RSYU3TyTpE3>V(wLc>M3xQMviB^-f0cj{(YxJ0(lpgPXEHd0qMRsFM}D`L3e"
    "4hc2)@4nhe8X~^BC7yFx-KALFrFiU{i3=a*#zw1r)2*HD>}H~np)Q{>)TJ1PXLPQJ&EJ#5557eC)hVRa"
    "xEViP>*2H7VF%80-I?2r*K0F8Tr$k|5p{4?^eb=jO+McoW~KG@p?k@7Xlv`k!|;;tx@>CS<tM3k*kf!f"
    "sGV2gfbIJBEZu8efII0lzUn!O962m2n1-LCH}A7(Z}ddOc0&I6-t%p>E47&G>SsRj8JN}5#pl$=2I!wT"
    "+DApcDy7fUhfV&qOiNq&iV)|TUckcIl8md@&Zg~#wjbuT4k7EcBiqw!&6NybbGi{8TA-mSfRps9oj%O_"
    ">sYm}qSVdcHq}W0dH3kPrs;8?0GR8JsOOh-UC5h=l`~$j-^)}}@$Klc(P63ed6mzGb~W<8)LeXE?^g9="
    "ml}?=&-cCfW17}|^W-*UU#~agz^i-UJo`%P-g$Sjuex@q>59MPeCdW^dIkp^KbbbW_@V2u``yI7@rKq;"
    "xllJyI1cro8<7W%`eFZ;k1q8;y6$=1@P_?v{>O*HkCZd0YLXt>y#M5`?)oDq)t||ZtkdV8yOE6k$a)cn"
    "cHc{a{i&U&b3%i<9o=I4&-RPs@@MBb_f-L;%+6BhPg}ZX*`F4Q#hk?3x^~r7?BIEAsPz=*LN(X@`A^pv"
    ">TrWPvrV|J;*T}IitInb<ff=lMwzTaL;m~1a@zjX@5CwjX`>`-yQ$0CP|HafR}0yQ;99lMSU5ZPy4Uep"
    "yL$MuE{Cq}FE-$(^AgFrZP(jsR^|P;ng2+VPv`xx2WF~fpF8KyT<^3!eD1ne)aT8oCvz_z=UrU!(Eh3@"
    "n8h~!j_u^y6ks=hR$pCPOWb@q*M#yKkeOV7pQE!{`KE10b<6nUN#HXv->*{~%V(vY&xJmZ;~S1`KDe(6"
    "fx!Rs;8L8OCJWcFpe|h%*>0iMnBi3L%w|>1mO0G#qMAcgeU5FXq}4x5TAgfDy;Q7n>WQ0b&f{;$O-SM|"
    "4diw+HOsf(n|rgIj=b1)3edOvv5MolF<c6_L)E+On7API7w@j_lkXQd{I`?cU3avHP1}#fo^ubz>7)*j"
    "lhaWp_EPbF_4*uR+dnx^Bmv}c^}=CBDtHdv-I>I8Pyg)vq6u%0-P0TM=krB!eQ(|mTH^)I<B_t?c{f)a"
    ";aiR$!QYtRZ+!33#^`)cgr76YEAM!d+#d}!OmWjvf@x;K{^lYnk#<!A_|&C*@x*+7!xrA=7z(q$^X1+0"
    "-a26$`SvF#QB6K>Dg=m&Tn-b4@**g(Y+dIJMGM<-ez}`x9?&=LQRs7*c|F1&Sqas@p0=#%WZoO{QorTv"
    "#w|ae-=rXsER&1ija~b03eSDd6xL61wq}~bB`S#}&2>?xIbW1%u9_dZ;ge@eLM|N>8+JvdOHoZ(-#L%5"
    "fFW6^N;K7^b1U7{GJ{AF;>P@O<q$_H7+!kx9Dl<0!!=AfuCvBz69U_bIJ&&9H?Qh6>nE2Es&?Mw-FlDt"
    "ePc>A>u={x{&uW5%K19~u6JUr%SRPVV1jd;{?(R&^B$L+ElsU4m>dN+e|}#0<1;bc6y?@Io6n%UUC=p3"
    "clgxA`^;~J$}M4dmg4Y)uyu8J*>0C#^G5!krg2{R-_+f1KMqt?^Y*ivk&VnwbGp$rx2Eauk3X)LzA9eA"
    "#(ZuhEOzVLy6z-KcV8}{-|lqNn`?SX2C{35Pso(ZYd2UAlZo5@h`aWukN)oK;*-ZOhS#LH)M!{^!U_kP"
    "M)O|ccTe}4&av5a!4wtVY%HN+Cfh(4PMUHd945&Nry%S$Fgb57NsG0bY-(nKJ>XoZX|>mm_I|FP?t9la"
    "3NItlxkSlwyRV>k%wheEb(foP>~_zac>j7|({)c?!06la<%y;n-?Mx@Q}^l}YNcuU_v^(5^j9pCmk1ks"
    "e-MO|gYxr2MKer<{!mQ!OT8FT^@pnG`wV^ile}`i{iPeF&G||x;9qA)=!~Ozad)E`tVYvaXsBP`u4sns"
    "i%uJ??xV9~_lK&QgC@U2<IvdlPIugXsEb-Bk$QBSP(9S1zN9<s!gT4#!}6UvdUS3aE7Oc7XB&;qHk#A#"
    "Y9ZE1jZcS5?M|*Hk9|GBBtb4GEuPaem2x**bDMSDYWb}5xsm6?SHqjRm*vZJ!DVvpc%rg<t*Gsmt`&J~"
    "x6~o$SEFxNJby80SDajT1A#tw#7>TsvlomJpw?wRzH8fA)!WrhD@kZjw=R$0uG(Y0!M@!yBl3XLIk~Fc"
    "wmwvxfxBJltkH5?p{>`8C0}A4Ua<~UZZB8tcE?wI$BM65?jEi_kYd*#cEhyWe-0tUuzG6z@x1}gu-(hv"
    "`<|{K;y(V>=5Jp<^~DyvV++JKykjHR()G&4QtwfT{AYTjzz)Bsj!t5TcOBoOyn4{x-0M|b&b1|^wbB&7"
    "OLH;9TIc;IM}i->A(D*$D9!A~8Qzxb-=)2Hew3#EU7CxRzI9#~btK@rhE_Y6o3C}>Tb?F6`vxzX!BjhZ"
    "lFs~qm-{VkIsU$u<iF91+VxtP^#t>y#9c6t67Gy|rZ?V&I}1Lj$WxVzZ`s=`J$M?Y7oG3O)9fF}{&RXa"
    "@l93BZkXL4*tFfxN$qK-7?Hhe33U0k5p_R2c3HoEDu+OWh52o>!zr)M$F>}=0efs^x8;q!JFI`5Vs8AG"
    "mW}^p8Q-lhNlf0s_>WdnvK{~7g1gUc^A8r1Z3*r8Pgd)FY5#@wcb~yOUx@eV|G|p9OL&@GRS=4l@yV+d"
    "_C5t>7;pGuE|@I2dDjmnN|AFmblzg}vR*NG3z4R`YDMJ!)+I|PF}Z!ibr56WC?J_NX2^C)^P1ehD5kIe"
    "VzfH(4bE(CKW@^c4wjUJd~o$lesr$&V}7|6-#L#Zy7pN0%YD7Y<{XQwxw+!dwf)G~V`j^Gv=19~zj}wi"
    "E1ukjB7x*5_hCp7`ShIOWGv%tHEUUv-PvR4{B}Thb{uxa?VGHO0q4{&&VsU==mnh==5Ce0{$f$LTE1gw"
    "-Z4DRCnJ|6kbHVE<=4)EglzjdkK}sic<a0xu(zzW{w8ijet!olE8l08aocTf*XTx>)`eqSrn~38qq_U7"
    "9q-^4@^|8?%O}ED@917gVA{F{kRJo%`z*8NakkBSDMa12cy1h%NEYXNF>-`$tGrj|Y$q#td+~yG?vD+O"
    "1xCSM>Fstu$M2oIbKTB4TKVoWSirdbK22Vbh{~T?$o$Ot!o_|$rR|=+CHKSj>Rq|+zw)l!?S6Itrd-$M"
    "@2iuSWxaFNrE_{%_f(WRP1VlXzg>Mg_is1+rpvnFeI4zZ@TNUF>pA?l`|O&(^83|DcfT0v+ftl0|L>3X"
    "gR#*4&0k1e$G5>8{^-tm&(~B|zQ>_ca`8=sI2F8pzqM`u<*Q!Z@J_l6jd^Xlp}cbf*ggMl(~d1hOcU+d"
    "J>hM=+hb<R>(>pR4ksG17ZEc$FN}7FdQOt|j=jsP2JE(mwx{jm@UB@0-7@KpF3)h#%-Kn^dc685y081U"
    "RXM@7`4<(;FZ;mEoGfHK+`G$Mj68h(>y!!RAk_f_Y!Yc+f0wQMg6Muu5*Sverwl9V0Dqkl;M`yQW@A}x"
    "M;P#!ROB9=2OWQ%cToQB^ZwJqlg{bIIsTUOwEQ*auS<98S8mSV*0aAoQR{Xyeg#cY(VADpsn!hK{jG*R"
    "AMQRtvIooAS<zo_=sE_t+wZ#Ve!Yeq>u+xI_7kNJnDgT5%WvnWBry7R`*2PU@HxL~x!ezYAA7L(NYydb"
    ";PR{jty_ebQuT_;rGbnAH#sovt2HlIUeeU}mr8oQ=hWBJ@+f(EOK`^2v-9`a$h(~sV6~d@M$Sc}>9@t}"
    "W5-^KQ@<@=<~A$q)wPpd3%j?8AqgO!$>DO}bWbMIjKi$^KE3nK@Smca^KiI<E>o9V>><7NK;smHw^f-P"
    "^gXYB;y&-Ozno^f_2rW@=vZuTlqP+fyH4qeCULcTJbLQ8%>DVbd^fgpQpqz6PrdDZu1?@U+pOz`@mI{`"
    "eLSNYy1f6p<#)B@DDNMO?YF~>XJXjwuXALW4E|7FX_E|wYr2VJyO+17|9K&~uZzvu^EW(x*>ebfBnzK`"
    "$zOP<c#b~12%cd%eWPc2J(hC5kI3Um`&i}O*Ug5)<?<e2PL+Gfo5A^Vf$1sGGb)%>vV?|WG8Dz3n-vGl"
    "MvR8;cMOv^d4G6@uH6k*pzHR`a5jPm=Z)fF%=@xF%Q$`*O`OF$PTuDcXZen^ZZ4a}P<}eO+pU~Z<>%$o"
    "seJq;<D)bl^ofn3Jie>ev9E0>87kKv!tWsE_15U+n{NmWRpabhqD3v;)N|UEo4OL!c~2eaI^WjcRr&Lw"
    "JgjP-pFea5L>{nI%<tcA1);Cj4sLEXe3jw+t>W7xt8%s}2d7D}`6~NXUlKfFm{zm%`QNY_UVU_fWHKFY"
    "zCy5~3OKBPE^YCdnC<UIbhh5MOL@nJ_4VDRVcncD+eg&&a-|O3ss1@A(v647OP;`7W@KI7?C4F8`1S3H"
    "Ve(@6<HwDM`sX7Sc>Xk0`*<5*aDMD)dY%lv(=QpPpY9sQJq)|isHbOS?t6oCS%0>=956VS@|D=VB91SJ"
    "+wzxIxx=nS;{O?oTzQR8t(76)s{fqAY^*xo-^=xMIgcFN!r*qAH|G5sCSUgj=DLkFlaDmsQEzXxF-F{X"
    "-My^l&*i~kS5Ce%J?x&CxFmqwzIFx<UGY0#{m{MJ=(|mChrvTPeWz=+=Sl-5w}oV0v-@8n5R$acwd3ON"
    "cE|1hK4rRY-S)cl&6(TqcUm*zM5&!06*NL{WeHyMI2<X*ydHkuVHzACIUM#&GbV<9KY8hSf0;b}$*nh{"
    "SN7Yh^)L+OWCj9tr8?h#Y0Lcc{vEF2#bv2MZj)h{>T|=7KIdAT12*=0x5g%CU-~2zuT$&U@8-x$3eT<U"
    "au~}O+*G9Qxn1ozLPSaL9h`@Tm(0!@)O~)BmyI`HUDZP<pS9d^`{HxSqjgR1{?ya;40jlhFKT7m?Omnz"
    "%li*+9hUrR(O8eB4m<CW0Xw^SH5SqC7hH$X`OVM^-Z&hK;EX1{c=BrtXA?&}&LKWXZ9DvU^M~ufHJ-j*"
    "=wtrsV>iQb<xn-+;`5jvs@duytB%eune=>#W><~Jw*MUFWD@J@D%UIm<muh?7Sp>~EvEJRdGVu$oqjR5"
    "#n-&xyX<<W_fryV<D;cLPG651gF|yw&BlDat(<Q4uidH;gUi<ltlo0QJ_iMDzrFo+4cA8>?3)jx`#4oU"
    "Z8IP3Fm)`ZTg0e?(y`*tboB1~;yq7qj84wSo(JYUCGo^xv6w8$TaKyHXYaa=(@%McRNDo?%hOAa$xCCf"
    "2p+3~jeLLcCX9|_Q>32}53244U9@h-h#MSN&LC;epI;u=2M7HKg}BQ{Oe0ll<NTURb5Ra?9aCd{^C5}R"
    "eiCN1ABwrhHO@(N{>1=ZW*n)DK`QjsZn{4&>+wPYlk*!xw;v9<k<6p>$Y|_q1Ul^)`^k#wb7zu$WnYdM"
    "d)J4a(Qi$?)4HEtBpxT;B6`pvzM2k(?Ac@-f4)*Y=1W+*&@Rx3a(2kKd#Qk<_G#Vm;U|Nu;%uLeKX-pd"
    "?W*H=wf3O(*(NkPo%KWAj8(Cjq3&e^qD_#a^J1Hu*C{vG)vj%16Oa27ED15b_^k1$JIv#BaqI*C{qI)o"
    "fA#g>{mNBSV7ErxzMyWW5@Ee17PRJ%D`AuWvAXT*@#|Q*oUS5~rF9;m6MdEe`@X((3?AiPHtgU;Z=LAD"
    "C6^5gs`GW@ef@WSS?T-zkFR3S&%(5_0{4f9Z?;xNHNUtV_f9=REayqTKdjzzJbdbuwDX-ckvI1rRV7&;"
    "WZfU?*9n_xLK8@$c2jC+*$z|6V3hG$TgLHcED!gW=l6%hes1r-;BlJu<yVV9eA&~#=;~ke^}Eh~(cAC3"
    "`%Qnp=<pXk{>v_Z+2^l2{q(GW{ch;00v398uFCf_PWwpe{`XnE$?3ok`d_X0!hQ<k;Bd+p<@w{3hvMez"
    "o<Awp&o|N^rr|E-)e<>4zi@rf4YPyOO=oVLTxTqY`o7l@XMZ2s<^AuG5kYkSYp?d9J-y#C4t;a;3BF#l"
    "<S>-aDlMvO@f>7{ABN#&%JC)j_=-C2?>>CSIIxaaj`(K%&r3$f;N?d~kGX@~wv9*=r`^%co?w&R97Zxm"
    "-0Akk(qVSgdEoK(SGHvD=iU5hKeu&U4(^`_;mbW+>Td&BFWwaU=`n``K^dNTUVNqflX}y!T)t!I9$%H#"
    "Ef$ih<&W4!q%qu&Ec?Oz<e>;~uJzS5_54_uYaK-%C*M~5A$<;SD&5>Km7}WB<PQU)lbB=UI<cD_br5rW"
    "_ucB_{jZj)@2%$>=l#MnLtz|)BklFFk)EGtVSJX+;jy`zfX(R<tqJJ-X!h)=Z_pg=KwA3p(R6+S{}xAQ"
    "`O$gJPT!}f`jwqM9lIy)CK5<~H;8|oW&G8+^sZMQCFn$*NU-D7^?3YoJsyXy1^#QoVdx9j=vph7&@d!)"
    "wdi<w?C}G8{PY_|{Uotub;k3#NIWg?(98O~OOW#YlytbGocn<I?<a(BSK;~eWyt(0M^E|mi&aCtJyiXc"
    "A0C^TMR;=lh8wV4dZ%UX`n98(@Fc(ad6Tx-n}_TAO4;e|()#IoS^YHqLS&J5x7SckZ+__U!u9++zo1>Y"
    "p8WX2g?#*7yU1HjU)2QalGF58$np_pXxk05s_)y&%ikyWC%w=0wl901+-Ba%%)HZP;(FNpXpyJ$2O^)-"
    "56|DLJ=OO=&2Tcm$jSM0VVE7&snE|7fT4N8@$`!D$$jzrHsh(#KW%TO%C>oz!SI%0`Ks!A3ukT%+S!7k"
    "d7s>w?w=oV-n<vooU>L|<GUt~FYEZ?J~@*9cdL2h<~ljQoqk)>n;VIZ;@jy@pAhfz)3w{Km<{{2^!`&j"
    "5ohgHCUnys3%KiP`}FhRC;pVoHT9ibyWUnmIlt*vLxgs!(6c=jgqvT`Id#WpA5|@2Kd{GlHtOB!myE-c"
    "KAfJ66Lo3j@LUF8Ste(_L|v$R_XiKY>+Lq5gL>gRG*6|`D@k>{y~lCluZXlq{kRQiU*GpX+C~J>Q)TN!"
    "{8zqv)PRKoW%A>{z?>`a?M-s~#`@XVXL%eycY8|>UQ)xC)aWHOeo0MUQqz~z+-2^61N}{-|MC%~=`96w"
    "27Ehzf&F`LY5MQy#HMk6j(S&as%<&bHxPN{kLyQu_<#TV{{vv{AKL"
)


def _load_tables() -> tuple[tuple[int, ...], dict[str, str]]:
    data = json.loads(zlib.decompress(base64.b85decode(_PACKED)))
    ranges: tuple[int, ...] = tuple(data[0])
    mime: dict[str, str] = data[1]
    if len(ranges) != 1957 or len(mime) != 1005:
        raise RuntimeError("Pinned document metadata tables are invalid")
    return ranges, mime


_RANGES, _MIME = _load_tables()
_ASCII_LOWER = str.maketrans("ABCDEFGHIJKLMNOPQRSTUVWXYZ", "abcdefghijklmnopqrstuvwxyz")


def _parts(name: str) -> tuple[str, str]:
    basename = name.replace("\\", "/").rsplit("/", 1)[-1]
    dot = basename.rfind(".")
    if dot <= 0:
        return basename, ""
    return basename[:dot], basename[dot + 1 :]


def _clean_part(part: str, limit: int) -> str:
    emitted: list[str] = []
    for character in part:
        if len(emitted) == limit:
            break
        kind = _RANGES[bisect_right(_RANGES, (ord(character) << 2) | 3) - 1] & 3
        if kind == 0:
            continue
        if kind == 1:
            character = " "
        if not emitted and character in " .":
            continue
        emitted.append(character)
    return "".join(emitted).rstrip(" .")


def clean_document_filename(decoded_name: str) -> str:
    """Clean an already decoded name with the pinned HTTP temporary-basename fallback."""
    if not isinstance(decoded_name, str):
        raise TypeError("Document filename must be a string")
    try:
        decoded_name.encode("utf-8")
    except UnicodeEncodeError:
        return "file"
    stem, extension = _parts(decoded_name)
    stem, extension = _clean_part(stem, 64), _clean_part(extension, 16)
    if extension:
        return stem + "." + extension if stem else extension
    return stem or "file"


def document_mime_type(cleaned_filename: str) -> str:
    """Derive only the pinned ASCII case-insensitive extension mapping; unknown is empty."""
    if not isinstance(cleaned_filename, str):
        raise TypeError("Cleaned document filename must be a string")
    return _MIME.get(_parts(cleaned_filename)[1].translate(_ASCII_LOWER), "")
