"""Actual Android inline-button input, real bot interruption and visible edit recovery."""

import http.client
import json
import re
import subprocess
import time
import xml.etree.ElementTree as ET
from collections.abc import Callable
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit

from android_guest import main
from callback_round_trip import run

from gramlab.world import World


def probe(adb: Callable[..., subprocess.CompletedProcess[str]]) -> dict[str, object]:
    capability = ""
    evidence: dict[str, Any] = {}
    guest_command = adb

    def checked_adb(*arguments: str, **kwargs: Any) -> subprocess.CompletedProcess[str]:
        result = guest_command(*arguments, **kwargs)
        if result.returncode:
            retain("guest-command-error.txt", result.stdout + result.stderr)
            raise RuntimeError(f"Guest command failed: {arguments[0]}")
        return result

    adb = checked_adb

    def retain(name: str, value: str) -> str:
        if capability and capability in value:
            raise RuntimeError("Client diagnostics contain a capability")
        Path(name).write_text(value)
        return value

    def launch() -> str:
        result = adb(
            "shell",
            "am",
            "start",
            "-W",
            "-n",
            "org.gramlab.android/org.telegram.ui.LaunchActivity",
            "-a",
            "com.tmessages.openchat",
            "--el",
            "userId",
            "2",
            timeout=40,
        )
        return result.stdout + result.stderr

    def screen(text: str, name: str) -> str:
        deadline = time.monotonic() + 30
        ui = ""
        ready = False
        while time.monotonic() < deadline:
            dump = adb(
                "shell", "uiautomator", "dump", "/data/local/tmp/callback-ui.xml", timeout=15
            )
            if dump.returncode == 0:
                ui = adb("shell", "cat", "/data/local/tmp/callback-ui.xml").stdout
                # The dump is generated by UIAutomator in this dedicated guest.
                outgoing = sum(
                    node.get("text", "").startswith("سلام hello\n")
                    for node in ET.fromstring(ui).iter("node")  # noqa: S314
                )
                if text in ui and outgoing == 1:
                    ready = True
                    break
            time.sleep(0.2)
        adb("shell", "screencap", "-p", "/data/local/tmp/callback-ui.png")
        adb("pull", "/data/local/tmp/callback-ui.png", f"/work/{name}.png")
        retain(f"{name}.xml", ui)
        retain(
            f"{name}-trace.jsonl",
            adb(
                "shell", "run-as", "org.gramlab.android", "cat", "files/gramlab/trace.jsonl"
            ).stdout,
        )
        retain(f"{name}-windows.txt", adb("shell", "dumpsys", "window", "windows").stdout)
        retain(f"{name}-logcat.txt", adb("logcat", "-d", "-t", "2000", "-v", "brief").stdout)
        if not ready:
            raise RuntimeError(f"Expected client content did not render during {name}")
        return ui

    def interact(configuration: dict[str, Any]) -> dict[str, Any]:
        nonlocal capability
        capability = configuration["capability"]
        installed = adb("install", "--no-streaming", "/work/client.apk", timeout=60)
        if installed.returncode:
            raise RuntimeError("Dedicated client installation failed")
        configured = adb(
            "shell",
            "-T",
            "run-as",
            "org.gramlab.android",
            "sh",
            "-c",
            "'mkdir -p files/gramlab && cat > files/gramlab/config.json'",
            input=json.dumps(
                configuration
                | {
                    "endpoint": configuration["endpoint"].replace("127.0.0.1", "10.0.2.2"),
                }
            ),
        )
        if configured.returncode:
            raise RuntimeError("Dedicated client configuration failed")
        evidence["launch"] = retain("launch.log", launch())
        ui = screen("تأیید ✓", "before-tap")
        evidence["before"] = ui
        candidates = []
        # XML comes only from UIAutomator in this dedicated guest, never from scenario input.
        for node in ET.fromstring(ui).iter("node"):  # noqa: S314
            if "تأیید ✓" not in node.get("text", "") + node.get("content-desc", ""):
                continue
            bounds = re.fullmatch(r"\[(\d+),(\d+)\]\[(\d+),(\d+)\]", node.get("bounds", ""))
            if bounds:
                left, top, right, bottom = map(int, bounds.groups())
                if right > left and bottom > top:
                    candidates.append(
                        (
                            (right - left) * (bottom - top),
                            (left + right) // 2,
                            (top + bottom) // 2,
                            node.attrib,
                        )
                    )
        if not candidates:
            raise RuntimeError("Rendered inline button has no accessible bounds")
        _, x, y, selected_node = min(candidates, key=lambda entry: entry[0])
        evidence["tap"] = {"x": x, "y": y, "node": selected_node}
        if adb("shell", "input", "tap", str(x), str(y)).returncode:
            raise RuntimeError("Dedicated guest input failed")
        retain(
            "immediate-tap-trace.jsonl",
            adb(
                "shell", "run-as", "org.gramlab.android", "cat", "files/gramlab/trace.jsonl"
            ).stdout,
        )
        deadline = time.monotonic() + 15
        while time.monotonic() < deadline:
            with World.open(Path("world")) as world:
                pending = world.poll_updates(2)
            callbacks = [
                update["callback_query"] for update in pending if "callback_query" in update
            ]
            if callbacks:
                endpoint = urlsplit(configuration["endpoint"])
                connection = http.client.HTTPConnection(endpoint.hostname, endpoint.port, timeout=5)
                try:
                    connection.request(
                        "GET",
                        "/v1/callbacks/" + callbacks[0]["id"],
                        headers={"Authorization": "Bearer " + capability},
                    )
                    response = connection.getresponse()
                    if response.status != 200:
                        raise RuntimeError("Tapped callback receipt unavailable")
                    return dict(json.loads(response.read()))
                finally:
                    connection.close()
            time.sleep(0.1)
        screen("تأیید ✓", "callback-timeout")
        raise RuntimeError("Actual inline tap did not create a bot callback")

    def observe() -> dict[str, Any]:
        evidence["edited"] = screen("تأیید شد ✓", "after-edit")
        if adb("shell", "am", "force-stop", "org.gramlab.android").returncode:
            raise RuntimeError("Dedicated client stop failed")
        evidence["restart_launch"] = retain("restart-launch.log", launch())
        evidence["restarted"] = screen("تأیید شد ✓", "after-restart")
        evidence["accounts"] = adb("shell", "dumpsys", "account").stdout
        return evidence

    try:
        return run(interact, observe)
    finally:
        guest_command("shell", "am", "force-stop", "org.gramlab.android")


if __name__ == "__main__":
    main(probe)
