#!/usr/bin/env python3
"""Verify committed rich-media fixtures against their generator and manifest."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from generate import generated_files


def main() -> None:
    fixture_directory = Path(__file__).resolve().parent
    expected_files = generated_files()
    for filename, expected in expected_files.items():
        actual = (fixture_directory / filename).read_bytes()
        if actual != expected:
            raise ValueError(f"fixture differs from generated bytes: {filename}")

    manifest = json.loads((fixture_directory / "manifest.json").read_text())
    for record in manifest["fixtures"]:
        contents = (fixture_directory / record["filename"]).read_bytes()
        if hashlib.sha256(contents).hexdigest() != record["sha256"]:
            raise ValueError(f"SHA-256 mismatch: {record['filename']}")


if __name__ == "__main__":
    main()
